apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-application-deployment
  labels:
    app: webapp
spec:
  replicas: 1  # Number of pods
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: java-app
          image: us-central1-docker.pkg.dev/abiding-honor-383407/project-repo/java-app:latest
          ports:
            - containerPort: 8080

