apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: nginx
spec:
  replicas: 1  # Number of pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: us-central1-docker.pkg.dev/abiding-honor-383407/java-app/hehealth-care:v3
          ports:
            - containerPort: 8080

