apiVersion: v1
kind: Service
metadata:
  name: java-application-service
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8080

