name: Build & Deploy Application

on:
  push: 
    branches:
     - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Set up JDK
       uses: actions/setup-java@v4
       with:
          java-version: '17'
          distribution: 'temurin'

     - name: Build jar with Maven
       run: mvn clean package -DskipTests

     - name: Set up Docker
       uses: docker/setup-buildx-action@v3

     - name: Configure Google Cloud credentials
       run: |
        echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcloud.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud.json
        gcloud config set project abiding-honor-383407
        gcloud auth configure-docker us-central1-docker.pkg.dev

     - name: Build Docker image
       run: |
          IMAGE=us-central1-docker.pkg.dev/abiding-honor-383407/project-repo/java-app:latest
          docker build -t $IMAGE .
          docker push $IMAGE
